name: Release on Tag Push

permissions:
  contents: write
  actions: write

on:
  push:
    tags:
      - 'v*'

jobs:
  package-and-release:
    name: Package and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      # Extraire la version du tag
      - name: Extract version from tag
        id: version
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG_NAME#v}"  # Remove 'v' prefix
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "📦 Version extraite du tag: $VERSION"

      # Install zip, required by BigWigs packager
      - name: Install zip
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      # Generate the "latest" changelog section
      - name: Generate changelog for latest tag (scoped)
        uses: tj-actions/git-cliff@8bfb7bf10268aed30bde8e34ecaeddb6c6149edd # v2
        with:
          args: --latest
          output: LATEST_CHANGELOG.md

      # Copy LATEST_CHANGELOG.md into CHANGELOG.md
      - name: Copy latest → CHANGELOG.md for packager
        run: cp LATEST_CHANGELOG.md CHANGELOG.md

      # Run BigWigs packager
      - name: Run BigWigs Packager (Retail)
        uses: BigWigsMods/packager@fd8ff7f95606c6d63c9a2d4d29c06e0abf1c3a60 # v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
        with:
          args: -g retail

      # Créer la release GitHub
      - name: Create GitHub Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2
        with:
          tag_name: ${{ steps.version.outputs.tag_name }}
          name: "GuildLogistics ${{ steps.version.outputs.version }}"
          body_path: LATEST_CHANGELOG.md
          draft: false
          prerelease: false
          make_latest: true

      # Notification finale
      - name: Final Summary
        run: |
          echo "## 🎉 Release complète automatique" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Tag**: ${{ steps.version.outputs.tag_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **GitHub Release**: ✅ Créée" >> $GITHUB_STEP_SUMMARY
          echo "- **CurseForge**: ✅ Package uploadé" >> $GITHUB_STEP_SUMMARY
