name: Generate Dynamic Package Config

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['GuildLogistics/**']

jobs:
  update-pkgmeta:
    name: Update .pkgmeta with current addon list
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0

      # Générer dynamiquement la liste des addons à ignorer
      - name: Generate dynamic .pkgmeta
        run: |
          echo "📦 Génération dynamique du .pkgmeta..."
          
          # Créer le début du fichier
          cat > .pkgmeta << 'EOF'
          package-as: GuildLogistics
          
          manual-changelog: CHANGELOG.md
          
          # Approche inclusive : on spécifie explicitement ce qu'on veut
          include:
              - GuildLogistics/
          
          # Fichiers/dossiers de développement à ignorer
          ignore:
              - .github/
              - .git/
              - .gitignore
              - .gitlab/
              - .vscode/
              - README.md
              - cliff.toml
              - LATEST_CHANGELOG.md
              - CHANGELOG.md
              - .pkgmeta
          EOF
          
          # Ajouter dynamiquement tous les autres dossiers d'addons
          echo "" >> .pkgmeta
          echo "    # Autres addons détectés automatiquement :" >> .pkgmeta
          
          # Lister tous les dossiers sauf GuildLogistics et les dossiers système
          find . -maxdepth 1 -type d -name "[!.]*" ! -name "GuildLogistics" | \
          sort | \
          while read dir; do
            dirname=$(basename "$dir")
            echo "    - $dirname/" >> .pkgmeta
          done
          
          # Ajouter la section move-folders
          cat >> .pkgmeta << 'EOF'
          
          # Déplacer le contenu de GuildLogistics/ à la racine de l'archive
          move-folders:
              GuildLogistics: /
          EOF
          
          echo "✅ .pkgmeta généré avec les addons actuels"
          echo ""
          echo "📋 Contenu généré :"
          cat .pkgmeta

      # Vérifier si le fichier a changé
      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet .pkgmeta; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "ℹ️ Aucun changement dans .pkgmeta"
          else
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "✅ .pkgmeta mis à jour"
          fi

      # Committer les changements si nécessaire
      - name: Commit updated .pkgmeta
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add .pkgmeta
          git commit -m "chore: update .pkgmeta with current addon list [skip ci]"
          git push
